/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReplenishRouteImport } from './routes/replenish'
import { Route as QuickScanRouteImport } from './routes/quick-scan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ObjectionsRouteImport } from './routes/objections'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ExpiryRouteImport } from './routes/expiry'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as DupesRouteImport } from './routes/dupes'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BeautyPassRouteImport } from './routes/beauty-pass'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicUniversityRouteImport } from './routes/api/public/university'
import { Route as ApiPublicTrustRouteImport } from './routes/api/public/trust'
import { Route as ApiPublicTrendsRouteImport } from './routes/api/public/trends'
import { Route as ApiPublicSosRouteImport } from './routes/api/public/sos'
import { Route as ApiPublicSkinDetectRouteImport } from './routes/api/public/skin-detect'
import { Route as ApiPublicSimulatorRouteImport } from './routes/api/public/simulator'
import { Route as ApiPublicReplenishRouteImport } from './routes/api/public/replenish'
import { Route as ApiPublicQuickAnalyzeRouteImport } from './routes/api/public/quick-analyze'
import { Route as ApiPublicProgressRouteImport } from './routes/api/public/progress'
import { Route as ApiPublicObjectionRouteImport } from './routes/api/public/objection'
import { Route as ApiPublicNextBestRouteImport } from './routes/api/public/next-best'
import { Route as ApiPublicDupesRouteImport } from './routes/api/public/dupes'
import { Route as ApiPublicCopilotRouteImport } from './routes/api/public/copilot'
import { Route as ApiPublicConflictsRouteImport } from './routes/api/public/conflicts'
import { Route as ApiPublicCompatRouteImport } from './routes/api/public/compat'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicBuilderRouteImport } from './routes/api/public/builder'
import { Route as ApiPublicAnalyzeRouteImport } from './routes/api/public/analyze'
import { Route as ApiPublicAcademyRouteImport } from './routes/api/public/academy'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplenishRoute = ReplenishRouteImport.update({
  id: '/replenish',
  path: '/replenish',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickScanRoute = QuickScanRouteImport.update({
  id: '/quick-scan',
  path: '/quick-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectionsRoute = ObjectionsRouteImport.update({
  id: '/objections',
  path: '/objections',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiryRoute = ExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DupesRoute = DupesRouteImport.update({
  id: '/dupes',
  path: '/dupes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyPassRoute = BeautyPassRouteImport.update({
  id: '/beauty-pass',
  path: '/beauty-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUniversityRoute = ApiPublicUniversityRouteImport.update({
  id: '/api/public/university',
  path: '/api/public/university',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrustRoute = ApiPublicTrustRouteImport.update({
  id: '/api/public/trust',
  path: '/api/public/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrendsRoute = ApiPublicTrendsRouteImport.update({
  id: '/api/public/trends',
  path: '/api/public/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSosRoute = ApiPublicSosRouteImport.update({
  id: '/api/public/sos',
  path: '/api/public/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSkinDetectRoute = ApiPublicSkinDetectRouteImport.update({
  id: '/api/public/skin-detect',
  path: '/api/public/skin-detect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSimulatorRoute = ApiPublicSimulatorRouteImport.update({
  id: '/api/public/simulator',
  path: '/api/public/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReplenishRoute = ApiPublicReplenishRouteImport.update({
  id: '/api/public/replenish',
  path: '/api/public/replenish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuickAnalyzeRoute = ApiPublicQuickAnalyzeRouteImport.update({
  id: '/api/public/quick-analyze',
  path: '/api/public/quick-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProgressRoute = ApiPublicProgressRouteImport.update({
  id: '/api/public/progress',
  path: '/api/public/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicObjectionRoute = ApiPublicObjectionRouteImport.update({
  id: '/api/public/objection',
  path: '/api/public/objection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNextBestRoute = ApiPublicNextBestRouteImport.update({
  id: '/api/public/next-best',
  path: '/api/public/next-best',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDupesRoute = ApiPublicDupesRouteImport.update({
  id: '/api/public/dupes',
  path: '/api/public/dupes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCopilotRoute = ApiPublicCopilotRouteImport.update({
  id: '/api/public/copilot',
  path: '/api/public/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConflictsRoute = ApiPublicConflictsRouteImport.update({
  id: '/api/public/conflicts',
  path: '/api/public/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCompatRoute = ApiPublicCompatRouteImport.update({
  id: '/api/public/compat',
  path: '/api/public/compat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuilderRoute = ApiPublicBuilderRouteImport.update({
  id: '/api/public/builder',
  path: '/api/public/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeRoute = ApiPublicAnalyzeRouteImport.update({
  id: '/api/public/analyze',
  path: '/api/public/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAcademyRoute = ApiPublicAcademyRouteImport.update({
  id: '/api/public/academy',
  path: '/api/public/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/academy': typeof ApiPublicAcademyRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/builder': typeof ApiPublicBuilderRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/compat': typeof ApiPublicCompatRoute
  '/api/public/conflicts': typeof ApiPublicConflictsRoute
  '/api/public/copilot': typeof ApiPublicCopilotRoute
  '/api/public/dupes': typeof ApiPublicDupesRoute
  '/api/public/next-best': typeof ApiPublicNextBestRoute
  '/api/public/objection': typeof ApiPublicObjectionRoute
  '/api/public/progress': typeof ApiPublicProgressRoute
  '/api/public/quick-analyze': typeof ApiPublicQuickAnalyzeRoute
  '/api/public/replenish': typeof ApiPublicReplenishRoute
  '/api/public/simulator': typeof ApiPublicSimulatorRoute
  '/api/public/skin-detect': typeof ApiPublicSkinDetectRoute
  '/api/public/sos': typeof ApiPublicSosRoute
  '/api/public/trends': typeof ApiPublicTrendsRoute
  '/api/public/trust': typeof ApiPublicTrustRoute
  '/api/public/university': typeof ApiPublicUniversityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/academy': typeof ApiPublicAcademyRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/builder': typeof ApiPublicBuilderRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/compat': typeof ApiPublicCompatRoute
  '/api/public/conflicts': typeof ApiPublicConflictsRoute
  '/api/public/copilot': typeof ApiPublicCopilotRoute
  '/api/public/dupes': typeof ApiPublicDupesRoute
  '/api/public/next-best': typeof ApiPublicNextBestRoute
  '/api/public/objection': typeof ApiPublicObjectionRoute
  '/api/public/progress': typeof ApiPublicProgressRoute
  '/api/public/quick-analyze': typeof ApiPublicQuickAnalyzeRoute
  '/api/public/replenish': typeof ApiPublicReplenishRoute
  '/api/public/simulator': typeof ApiPublicSimulatorRoute
  '/api/public/skin-detect': typeof ApiPublicSkinDetectRoute
  '/api/public/sos': typeof ApiPublicSosRoute
  '/api/public/trends': typeof ApiPublicTrendsRoute
  '/api/public/trust': typeof ApiPublicTrustRoute
  '/api/public/university': typeof ApiPublicUniversityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/academy': typeof ApiPublicAcademyRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/builder': typeof ApiPublicBuilderRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/compat': typeof ApiPublicCompatRoute
  '/api/public/conflicts': typeof ApiPublicConflictsRoute
  '/api/public/copilot': typeof ApiPublicCopilotRoute
  '/api/public/dupes': typeof ApiPublicDupesRoute
  '/api/public/next-best': typeof ApiPublicNextBestRoute
  '/api/public/objection': typeof ApiPublicObjectionRoute
  '/api/public/progress': typeof ApiPublicProgressRoute
  '/api/public/quick-analyze': typeof ApiPublicQuickAnalyzeRoute
  '/api/public/replenish': typeof ApiPublicReplenishRoute
  '/api/public/simulator': typeof ApiPublicSimulatorRoute
  '/api/public/skin-detect': typeof ApiPublicSkinDetectRoute
  '/api/public/sos': typeof ApiPublicSosRoute
  '/api/public/trends': typeof ApiPublicTrendsRoute
  '/api/public/trust': typeof ApiPublicTrustRoute
  '/api/public/university': typeof ApiPublicUniversityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/mcp'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sitemap.xml'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/academy'
    | '/api/public/analyze'
    | '/api/public/builder'
    | '/api/public/chat'
    | '/api/public/compat'
    | '/api/public/conflicts'
    | '/api/public/copilot'
    | '/api/public/dupes'
    | '/api/public/next-best'
    | '/api/public/objection'
    | '/api/public/progress'
    | '/api/public/quick-analyze'
    | '/api/public/replenish'
    | '/api/public/simulator'
    | '/api/public/skin-detect'
    | '/api/public/sos'
    | '/api/public/trends'
    | '/api/public/trust'
    | '/api/public/university'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/mcp'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sitemap.xml'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/academy'
    | '/api/public/analyze'
    | '/api/public/builder'
    | '/api/public/chat'
    | '/api/public/compat'
    | '/api/public/conflicts'
    | '/api/public/copilot'
    | '/api/public/dupes'
    | '/api/public/next-best'
    | '/api/public/objection'
    | '/api/public/progress'
    | '/api/public/quick-analyze'
    | '/api/public/replenish'
    | '/api/public/simulator'
    | '/api/public/skin-detect'
    | '/api/public/sos'
    | '/api/public/trends'
    | '/api/public/trust'
    | '/api/public/university'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/mcp'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sitemap.xml'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/academy'
    | '/api/public/analyze'
    | '/api/public/builder'
    | '/api/public/chat'
    | '/api/public/compat'
    | '/api/public/conflicts'
    | '/api/public/copilot'
    | '/api/public/dupes'
    | '/api/public/next-best'
    | '/api/public/objection'
    | '/api/public/progress'
    | '/api/public/quick-analyze'
    | '/api/public/replenish'
    | '/api/public/simulator'
    | '/api/public/skin-detect'
    | '/api/public/sos'
    | '/api/public/trends'
    | '/api/public/trust'
    | '/api/public/university'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRoute
  BeautyPassRoute: typeof BeautyPassRoute
  BuilderRoute: typeof BuilderRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  ConflictsRoute: typeof ConflictsRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DecideRoute: typeof DecideRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DupesRoute: typeof DupesRoute
  EditProfileRoute: typeof EditProfileRoute
  ExpiryRoute: typeof ExpiryRoute
  FounderRoute: typeof FounderRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ObjectionsRoute: typeof ObjectionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuickScanRoute: typeof QuickScanRoute
  ReplenishRoute: typeof ReplenishRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SimulatorRoute: typeof SimulatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SosRoute: typeof SosRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  TrendsRoute: typeof TrendsRoute
  TrustRoute: typeof TrustRoute
  UniversityRoute: typeof UniversityRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAcademyRoute: typeof ApiPublicAcademyRoute
  ApiPublicAnalyzeRoute: typeof ApiPublicAnalyzeRoute
  ApiPublicBuilderRoute: typeof ApiPublicBuilderRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicCompatRoute: typeof ApiPublicCompatRoute
  ApiPublicConflictsRoute: typeof ApiPublicConflictsRoute
  ApiPublicCopilotRoute: typeof ApiPublicCopilotRoute
  ApiPublicDupesRoute: typeof ApiPublicDupesRoute
  ApiPublicNextBestRoute: typeof ApiPublicNextBestRoute
  ApiPublicObjectionRoute: typeof ApiPublicObjectionRoute
  ApiPublicProgressRoute: typeof ApiPublicProgressRoute
  ApiPublicQuickAnalyzeRoute: typeof ApiPublicQuickAnalyzeRoute
  ApiPublicReplenishRoute: typeof ApiPublicReplenishRoute
  ApiPublicSimulatorRoute: typeof ApiPublicSimulatorRoute
  ApiPublicSkinDetectRoute: typeof ApiPublicSkinDetectRoute
  ApiPublicSosRoute: typeof ApiPublicSosRoute
  ApiPublicTrendsRoute: typeof ApiPublicTrendsRoute
  ApiPublicTrustRoute: typeof ApiPublicTrustRoute
  ApiPublicUniversityRoute: typeof ApiPublicUniversityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replenish': {
      id: '/replenish'
      path: '/replenish'
      fullPath: '/replenish'
      preLoaderRoute: typeof ReplenishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-scan': {
      id: '/quick-scan'
      path: '/quick-scan'
      fullPath: '/quick-scan'
      preLoaderRoute: typeof QuickScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objections': {
      id: '/objections'
      path: '/objections'
      fullPath: '/objections'
      preLoaderRoute: typeof ObjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiry': {
      id: '/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof ExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dupes': {
      id: '/dupes'
      path: '/dupes'
      fullPath: '/dupes'
      preLoaderRoute: typeof DupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty-pass': {
      id: '/beauty-pass'
      path: '/beauty-pass'
      fullPath: '/beauty-pass'
      preLoaderRoute: typeof BeautyPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/university': {
      id: '/api/public/university'
      path: '/api/public/university'
      fullPath: '/api/public/university'
      preLoaderRoute: typeof ApiPublicUniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trust': {
      id: '/api/public/trust'
      path: '/api/public/trust'
      fullPath: '/api/public/trust'
      preLoaderRoute: typeof ApiPublicTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trends': {
      id: '/api/public/trends'
      path: '/api/public/trends'
      fullPath: '/api/public/trends'
      preLoaderRoute: typeof ApiPublicTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sos': {
      id: '/api/public/sos'
      path: '/api/public/sos'
      fullPath: '/api/public/sos'
      preLoaderRoute: typeof ApiPublicSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/skin-detect': {
      id: '/api/public/skin-detect'
      path: '/api/public/skin-detect'
      fullPath: '/api/public/skin-detect'
      preLoaderRoute: typeof ApiPublicSkinDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/simulator': {
      id: '/api/public/simulator'
      path: '/api/public/simulator'
      fullPath: '/api/public/simulator'
      preLoaderRoute: typeof ApiPublicSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/replenish': {
      id: '/api/public/replenish'
      path: '/api/public/replenish'
      fullPath: '/api/public/replenish'
      preLoaderRoute: typeof ApiPublicReplenishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quick-analyze': {
      id: '/api/public/quick-analyze'
      path: '/api/public/quick-analyze'
      fullPath: '/api/public/quick-analyze'
      preLoaderRoute: typeof ApiPublicQuickAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/progress': {
      id: '/api/public/progress'
      path: '/api/public/progress'
      fullPath: '/api/public/progress'
      preLoaderRoute: typeof ApiPublicProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/objection': {
      id: '/api/public/objection'
      path: '/api/public/objection'
      fullPath: '/api/public/objection'
      preLoaderRoute: typeof ApiPublicObjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/next-best': {
      id: '/api/public/next-best'
      path: '/api/public/next-best'
      fullPath: '/api/public/next-best'
      preLoaderRoute: typeof ApiPublicNextBestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dupes': {
      id: '/api/public/dupes'
      path: '/api/public/dupes'
      fullPath: '/api/public/dupes'
      preLoaderRoute: typeof ApiPublicDupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/copilot': {
      id: '/api/public/copilot'
      path: '/api/public/copilot'
      fullPath: '/api/public/copilot'
      preLoaderRoute: typeof ApiPublicCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conflicts': {
      id: '/api/public/conflicts'
      path: '/api/public/conflicts'
      fullPath: '/api/public/conflicts'
      preLoaderRoute: typeof ApiPublicConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/compat': {
      id: '/api/public/compat'
      path: '/api/public/compat'
      fullPath: '/api/public/compat'
      preLoaderRoute: typeof ApiPublicCompatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/builder': {
      id: '/api/public/builder'
      path: '/api/public/builder'
      fullPath: '/api/public/builder'
      preLoaderRoute: typeof ApiPublicBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze': {
      id: '/api/public/analyze'
      path: '/api/public/analyze'
      fullPath: '/api/public/analyze'
      preLoaderRoute: typeof ApiPublicAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/academy': {
      id: '/api/public/academy'
      path: '/api/public/academy'
      fullPath: '/api/public/academy'
      preLoaderRoute: typeof ApiPublicAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRoute,
  BeautyPassRoute: BeautyPassRoute,
  BuilderRoute: BuilderRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  ConflictsRoute: ConflictsRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DecideRoute: DecideRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DupesRoute: DupesRoute,
  EditProfileRoute: EditProfileRoute,
  ExpiryRoute: ExpiryRoute,
  FounderRoute: FounderRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ObjectionsRoute: ObjectionsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  QuickScanRoute: QuickScanRoute,
  ReplenishRoute: ReplenishRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SimulatorRoute: SimulatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SosRoute: SosRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  TrendsRoute: TrendsRoute,
  TrustRoute: TrustRoute,
  UniversityRoute: UniversityRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAcademyRoute: ApiPublicAcademyRoute,
  ApiPublicAnalyzeRoute: ApiPublicAnalyzeRoute,
  ApiPublicBuilderRoute: ApiPublicBuilderRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicCompatRoute: ApiPublicCompatRoute,
  ApiPublicConflictsRoute: ApiPublicConflictsRoute,
  ApiPublicCopilotRoute: ApiPublicCopilotRoute,
  ApiPublicDupesRoute: ApiPublicDupesRoute,
  ApiPublicNextBestRoute: ApiPublicNextBestRoute,
  ApiPublicObjectionRoute: ApiPublicObjectionRoute,
  ApiPublicProgressRoute: ApiPublicProgressRoute,
  ApiPublicQuickAnalyzeRoute: ApiPublicQuickAnalyzeRoute,
  ApiPublicReplenishRoute: ApiPublicReplenishRoute,
  ApiPublicSimulatorRoute: ApiPublicSimulatorRoute,
  ApiPublicSkinDetectRoute: ApiPublicSkinDetectRoute,
  ApiPublicSosRoute: ApiPublicSosRoute,
  ApiPublicTrendsRoute: ApiPublicTrendsRoute,
  ApiPublicTrustRoute: ApiPublicTrustRoute,
  ApiPublicUniversityRoute: ApiPublicUniversityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
