/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReplenishRouteImport } from './routes/replenish'
import { Route as QuickScanRouteImport } from './routes/quick-scan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ObjectionsRouteImport } from './routes/objections'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ExpiryRouteImport } from './routes/expiry'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as DupesRouteImport } from './routes/dupes'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BeautyPassRouteImport } from './routes/beauty-pass'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'

const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplenishRoute = ReplenishRouteImport.update({
  id: '/replenish',
  path: '/replenish',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickScanRoute = QuickScanRouteImport.update({
  id: '/quick-scan',
  path: '/quick-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectionsRoute = ObjectionsRouteImport.update({
  id: '/objections',
  path: '/objections',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiryRoute = ExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DupesRoute = DupesRouteImport.update({
  id: '/dupes',
  path: '/dupes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyPassRoute = BeautyPassRouteImport.update({
  id: '/beauty-pass',
  path: '/beauty-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRoute
  BeautyPassRoute: typeof BeautyPassRoute
  BuilderRoute: typeof BuilderRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  ConflictsRoute: typeof ConflictsRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DecideRoute: typeof DecideRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DupesRoute: typeof DupesRoute
  EditProfileRoute: typeof EditProfileRoute
  ExpiryRoute: typeof ExpiryRoute
  FounderRoute: typeof FounderRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ObjectionsRoute: typeof ObjectionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuickScanRoute: typeof QuickScanRoute
  ReplenishRoute: typeof ReplenishRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SimulatorRoute: typeof SimulatorRoute
  SosRoute: typeof SosRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  TrendsRoute: typeof TrendsRoute
  TrustRoute: typeof TrustRoute
  UniversityRoute: typeof UniversityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replenish': {
      id: '/replenish'
      path: '/replenish'
      fullPath: '/replenish'
      preLoaderRoute: typeof ReplenishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-scan': {
      id: '/quick-scan'
      path: '/quick-scan'
      fullPath: '/quick-scan'
      preLoaderRoute: typeof QuickScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objections': {
      id: '/objections'
      path: '/objections'
      fullPath: '/objections'
      preLoaderRoute: typeof ObjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiry': {
      id: '/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof ExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dupes': {
      id: '/dupes'
      path: '/dupes'
      fullPath: '/dupes'
      preLoaderRoute: typeof DupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty-pass': {
      id: '/beauty-pass'
      path: '/beauty-pass'
      fullPath: '/beauty-pass'
      preLoaderRoute: typeof BeautyPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRoute,
  BeautyPassRoute: BeautyPassRoute,
  BuilderRoute: BuilderRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  ConflictsRoute: ConflictsRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DecideRoute: DecideRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DupesRoute: DupesRoute,
  EditProfileRoute: EditProfileRoute,
  ExpiryRoute: ExpiryRoute,
  FounderRoute: FounderRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ObjectionsRoute: ObjectionsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  QuickScanRoute: QuickScanRoute,
  ReplenishRoute: ReplenishRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SimulatorRoute: SimulatorRoute,
  SosRoute: SosRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  TrendsRoute: TrendsRoute,
  TrustRoute: TrustRoute,
  UniversityRoute: UniversityRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
