/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReplenishRouteImport } from './routes/replenish'
import { Route as QuickScanRouteImport } from './routes/quick-scan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ObjectionsRouteImport } from './routes/objections'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ExpiryRouteImport } from './routes/expiry'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as DupesRouteImport } from './routes/dupes'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BeautyPassRouteImport } from './routes/beauty-pass'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'

const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplenishRoute = ReplenishRouteImport.update({
  id: '/replenish',
  path: '/replenish',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickScanRoute = QuickScanRouteImport.update({
  id: '/quick-scan',
  path: '/quick-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectionsRoute = ObjectionsRouteImport.update({
  id: '/objections',
  path: '/objections',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiryRoute = ExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DupesRoute = DupesRouteImport.update({
  id: '/dupes',
  path: '/dupes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyPassRoute = BeautyPassRouteImport.update({
  id: '/beauty-pass',
  path: '/beauty-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/beauty-pass': typeof BeautyPassRoute
  '/builder': typeof BuilderRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/conflicts': typeof ConflictsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dupes': typeof DupesRoute
  '/edit-profile': typeof EditProfileRoute
  '/expiry': typeof ExpiryRoute
  '/founder': typeof FounderRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/objections': typeof ObjectionsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quick-scan': typeof QuickScanRoute
  '/replenish': typeof ReplenishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/simulator': typeof SimulatorRoute
  '/sos': typeof SosRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/trends': typeof TrendsRoute
  '/trust': typeof TrustRoute
  '/university': typeof UniversityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/admin'
    | '/beauty-pass'
    | '/builder'
    | '/chat'
    | '/compare'
    | '/conflicts'
    | '/copilot'
    | '/dashboard'
    | '/decide'
    | '/delete-account'
    | '/dupes'
    | '/edit-profile'
    | '/expiry'
    | '/founder'
    | '/history'
    | '/login'
    | '/objections'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/quick-scan'
    | '/replenish'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/simulator'
    | '/sos'
    | '/terms'
    | '/tools'
    | '/trends'
    | '/trust'
    | '/university'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRoute
  BeautyPassRoute: typeof BeautyPassRoute
  BuilderRoute: typeof BuilderRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  ConflictsRoute: typeof ConflictsRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DecideRoute: typeof DecideRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DupesRoute: typeof DupesRoute
  EditProfileRoute: typeof EditProfileRoute
  ExpiryRoute: typeof ExpiryRoute
  FounderRoute: typeof FounderRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ObjectionsRoute: typeof ObjectionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuickScanRoute: typeof QuickScanRoute
  ReplenishRoute: typeof ReplenishRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SimulatorRoute: typeof SimulatorRoute
  SosRoute: typeof SosRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  TrendsRoute: typeof TrendsRoute
  TrustRoute: typeof TrustRoute
  UniversityRoute: typeof UniversityRoute
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
